### ISSUE TITLE
uptime demo - package not found

### ISSUE THREAD

**Issue by iftahnaf** [Minipada/ros2_data_collection#140]
**Describe the bug**
While running the `Uptime` demo from docker, `minipada/ros2_data_collection:humble-source-sim`, I'm getting the error:
`ros2 launch dc_demos uptime_stdout.launch.py
Package 'dc_demos' not found: "package 'dc_demos' not found, searching: ['/opt/ros/humble']"
`

**To Reproduce**
Steps to reproduce the behavior and DC configuration. If possible, provide a minimal amount of code that causes the bug.
1. after pulling the docker image, In one terminal: `docker compose up` and in the second `docker exec -it ros2-data-collection bash`
2. sourcing the underlay with `source /opt/ros/humble/setup.bash` (without it Im getting `ros2 command not found`)
3. trying to run `ros2 launch dc_demos uptime_stdout.launch.py` but Im getting the error above.

**Expected behavior**
The example should work as written in the documentation.

**Actual behavior**
`ros2 launch dc_demos uptime_stdout.launch.py
Package 'dc_demos' not found: "package 'dc_demos' not found, searching: ['/opt/ros/humble']"
`

**Screenshots, gifs**
![image](https://github.com/Minipada/ros2_data_collection/assets/58637596/d3379e35-1054-45cb-9d26-e4aa571a73cd)

**Infrastructure description**
Docker - `minipada/ros2_data_collection:humble-source-sim` running on ubuntu 22.04

**Additional context**
This project is amazing, great job!

**Comment by Minipada** [comment]
Hi @iftahnaf , thanks for the issue report and the feedback!
I tested here and I get the same issues.

1. First issue is that the docker compose workspace path is wrong, it should be like this:

```yaml
version: "3.9"
x-logging:
  &x-logging
  options:
    max-size: 50m
    max-file: "1"
  driver: json-file
x-restart: &x-restart "unless-stopped"
x-stop-grace-period: &x-stop-grace-period "3s"

services:
  ros2-data-collection2:
    image: minipada/ros2_data_collection:humble-source-sim
    privileged: true
    container_name: ros2-data-collection2
    environment:
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
      - DISPLAY=unix$DISPLAY
      - XAUTHORITY=$XAUTHORITY
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}:/root/ros2_data_collection/src/ros2_data_collection
    network_mode: "host"
    logging: *x-logging
    restart: *x-restart
    stop_grace_period: *x-stop-grace-period
    runtime: nvidia
    command: tail -F anything
    working_dir: /root/ros2_data_collection
```

2. After having killed and restarted the container (`docker compose down` and then `docker compose up`), I see is that the container is created, load the entrypoint, but `docker exec -it ...` does not load it, I could get around it by executing `docker exec -it ros2-data-collection2 /ros_entrypoint.sh bash`
I will submit a PR and ask you to verify
